version: "3.8"

services:
  # Frontend build service
  frontend-builder:
    image: node:20
    container_name: cryptoverify-frontend-builder
    working_dir: /srv/frontend
    environment:
      NODE_ENV: production
      # Explicitly set React env vars to ensure they're injected during build
      REACT_APP_ENABLE_CMS: "true"
      REACT_APP_CMS_URL: "https://api.gambleverify.com"
      REACT_APP_CMS_TOKEN: ""
      REACT_APP_SITE_URL: "https://app.gambleverify.com"
      REACT_APP_SITE_NAME: "CryptoVerify"
      REACT_APP_TELEGRAM_URL: "https://t.me/cryptoverify"
      REACT_APP_WHATSAPP_URL: "https://wa.me/1234567890"
      REACT_APP_DISCORD_URL: "https://discord.gg/cryptoverify"
    command: sh -c "npm ci && npm run build"
    volumes:
      - ../frontend:/srv/frontend
    restart: "no"  # Only run once

  caddy:
    image: caddy:2-alpine
    container_name: cryptoverify-caddy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
      # Serve frontend static assets (build output)
      - ../frontend/build:/srv/www:ro
    depends_on:
      frontend-builder:
        condition: service_completed_successfully
      strapi:
        condition: service_started

  strapi:
    image: node:20
    container_name: cryptoverify-strapi-prod
    working_dir: /srv/app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      HOST: 0.0.0.0
      PORT: 1337
      # Force Node/Koa to trust proxy headers and recognize HTTPS
      NODE_TRUST_PROXY: "true"
    env_file:
      - ../backend/.env.production
    command: sh -c "npm ci && npm run build && npm run start"
    expose:
      - "1337"
    volumes:
      # Mount codebase for simple rollout; you can switch to a built image later
      - ../backend:/srv/app
      # Persist database (SQLite) and uploads outside of code tree
      - strapi_db:/srv/app/.tmp
      - strapi_uploads:/srv/app/public/uploads

volumes:
  caddy_data:
  caddy_config:
  strapi_db:
  strapi_uploads:
